version: '3.7'
services:
  hashtopolis-backend:
    container_name: hashtopolis-backend
    image: hashtopolis/backend:latest
    restart: always
    volumes:
      - hashtopolis:/usr/local/share/hashtopolis:Z
    environment:
      HASHTOPOLIS_DB_USER: hashtopolis
      HASHTOPOLIS_DB_PASS: hashtopolis
      HASHTOPOLIS_DB_HOST: db
      HASHTOPOLIS_DB_DATABASE: hashtopolis
      HASHTOPOLIS_ADMIN_USER: admin
      HASHTOPOLIS_ADMIN_PASSWORD: hashtopolis
      HASHTOPOLIS_APIV2_ENABLE: 1
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: yes
      MYSQL_DATABASE: hashtopolis
      MYSQL_USER: hashtopolis
      MYSQL_PASSWORD: hashtopolis
  hashtopolis-frontend:
    container_name: hashtopolis-frontend
    image: hashtopolis/frontend:latest
    environment:
      HASHTOPOLIS_BACKEND_URL: http://localhost:8080/api/v2
    restart: always
    depends_on: 
      - hashtopolis-backend
    ports:
      - 4200:80
volumes:
  db:
  hashtopolis:
